server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: hotel-booking-api
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

---

# ===================================================================
# DEVELOPMENT PROFILE (dev)
# ===================================================================
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/hotelbooking_db_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password:

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 930c31001@smtp-brevo.com   # <-- Replace this with Brevo SMTP username
    password: IWqbN7RHUhKkgBfE   # <-- Replace this with Brevo SMTP password
    protocol: smtp
    properties:
      mail:
        smtp:
          from: buntheng@bakongcity.city
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl.trust: smtp-relay.brevo.com
        debug: true

app:
  jwt:
    secret: "k2iV7N3pR9sX6vB0tJg8FzW5LmZ1xQe4UkAjNcEyGhTwRyPoDuCvBxMzLsKaQdEr"
    expiration-ms: 86400000

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.hotelbooking: DEBUG
    com.sun.mail: DEBUG
    jakarta.mail: DEBUG

---

# ===================================================================
# PRODUCTION PROFILE (prod)
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mysql-1d18ad22-bunthengseng9-7dfc.f.aivencloud.com:17288/defaultdb?useSSL=true&sslMode=REQUIRED
    username: avnadmin
    password: AVNS_XnbWgpJfp01ff59Abur

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAILTRAP_USERNAME:}
    password: ${MAILTRAP_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwt:
    secret: ${JWT_SECRET:k2iV7N3pR9sX6vB0tJg8FzW5LmZ1xQe4UkAjNcEyGhTwRyPoDuCvBxMzLsKaQdEr}
    expiration-ms: 86400000

logging:
  level:
    root: WARN
    com.hotelbooking: INFO