
server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: hotel-booking-api
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update
# --- Swagger / OpenAPI Configuration ---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

---
# ===================================================================
# DEVELOPMENT PROFILE (dev)
# Activated when running locally.
# ===================================================================
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/hotelbooking_db_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_DEV_USERNAME:root}
    password: ${DB_DEV_PASSWORD:}

app:
  jwt:
    secret: "k2iV7N3pR9sX6vB0tJg8FzW5LmZ1xQe4UkAjNcEyGhTwRyPoDuCvBxMzLsKaQdEr"
    expiration-ms: 86400000
twilio:
  account_sid: ACbbbf8b23e65804b2f6e5c504e775d52a
  auth_token: efd1713ab057f2c13517ed7408deec60
  phone_number: "+15076876214"
logging:
  level:

    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.hotelbooking: DEBUG

---


# ===================================================================
# PRODUCTION PROFILE (prod)
# Activated when deploying to a live server.
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql-1d18ad22-bunthengseng9-7dfc.f.aivencloud.com:17288/defaultdb?useSSL=true&sslMode=REQUIRED
    username: avnadmin
    password: AVNS_XnbWgpJfp01ff59Abur
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        mail:
          host: sandbox.smtp.mailtrap.io
          port: 2525
          username: 8783992d414e97
          password: 8cd02c80c3e8fe
          properties:
            mail:
              smtp:
                auth: true
                starttls:
                  enable: true
logging:
  level:
    root: WARN
    com.hotelbooking: INFO


